### ISSUE TITLE
Process imported LESS sources

### ISSUE THREAD

**Issue by sntran** [shellscape/postcss-less#120]
* Node Version: v8.9.4
* NPM Version: 6.4.1
* postcss Version: 7.0.5
* postcss-less Version: 3.0.2

### LESS

bug.less
```less
// less that demonstrates the issue
@import "next.less";

body {
  margin: 0 auto;
  display: flex;
  flex-direction: column;
}
```

next.less
```less
body {
  font-family: system-ui;
}

.example {
  display: grid;
}
```

### JavaScript

```js
// js that reproduces the issue
const fs = require(`fs`);
const path = require(`path`);
const postcss = require(`postcss`);
const less = require(`less`);
const syntax = require(`postcss-less`);
const LessPluginCleanCSS = require(`less-plugin-clean-css`);
const postcssPresetEnv = require(`postcss-preset-env`);

fs.readFile(`bug.less`, `utf8`, (err, lessInput) => {
  postcss([
    postcssPresetEnv({
      stage: 2
    })
  ])
  .process(lessInput, {
    syntax: syntax,
    from: `bug.less`,
    to: `bug.min.css`
  })
  .then(result => {
    const {content, map} = result;
    return less.render(content, {
      filename: `bug.less`,
      plugins: [
        // new LessPluginCleanCSS({advanced: true})
      ],
      sourceMap: {
        sourceMapRootpath: `/`
      }
    })
  }, console.error.bind(console.log, 'PostCSS:'))
  .then(result => {
    const {css, map, imports} = result;
    fs.writeFile(`bug.css`, css + `\n/*# sourceMappingURL=${path.basename(paths.styles.map)} */`, noop);
    fs.writeFile(`bug.min.css.map`, map, noop);
  }, console.error.bind(console, 'Less:'));
});
```

### Expected Behavior

Should output the following CSS:

```css
body {
  font-family: system-ui, -apple-system, Segoe UI, Roboto, Noto Sans, Ubuntu, Cantarell, Helvetica Neue;
}
.example {
  display: -ms-grid;
  display: grid;
}
body {
  margin: 0 auto;
  display: -ms-flexbox;
  display: flex;
  -ms-flex-direction: column;
  flex-direction: column;
}
```

### Actual Behavior

Only the styles in `bug.less` are prefixed. The ones in `next.less` stay the same.

```css
body {
  font-family: system-ui;
}
.example {
  display: grid;
}
body {
  margin: 0 auto;
  display: -ms-flexbox;
  display: flex;
  -ms-flex-direction: column;
  flex-direction: column;
}
```

### How can we reproduce the behavior?

- `npm install --save-dev postcss postcss-less postcss-preset-env less less-plugin-clean-css`
- Create `bug.less`, `next.less` and the `index.js` file with content as above.
- `node index.js`
- Check `bug.min.css`.

For the context, `postcss-preset-env` converts `system-ui` to `system-ui, -apple-system, Segoe UI, Roboto, Ubuntu, Cantarell, Noto Sans, sans-serif`.

The second step of compiling LESS to CSS is not important. We can `console.log(content)` in the first pass to see the parsed LESS to see that the prefixes are only added to `bug.less`, and not `next.less`.

If this is the correct behaviour, please advise on how to handle imported LESS files to have transformation applied, as this is a very common pattern with LESS. I definitely don't want to write a single LESS file.

I have also tried `posscss-import`, but because it put the imported LESS files inline, it messes up my source maps. I want the source maps to point to original LESS files.
