### ISSUE TITLE
Support `each` function

### ISSUE THREAD

**Issue by iKonan-ru** [shellscape/postcss-less#121]
LESS 3.7.0 introduces `each` function: http://lesscss.org/functions/#list-functions-each
Postcss-less should support it.

* Node Version: 8.12.0
* NPM Version: 6.4.1
* postcss Version: 7.0.5
* postcss-less Version: 3.0.2

### LESS
```less
@colors: red, green, blue;
each(@colors, {
    .@{value}-color {
        color: @value;
    }
});
```

### Errors
```
Unknown word   CssSyntaxError
```

### Expected Behavior
Process `each` function normally.

### Actual Behavior
Having errors.
