### ISSUE TITLE
'Unknown word' for valid LESS

### ISSUE THREAD

**Issue by eddie-dunn** [shellscape/postcss-less#128]
* Node Version: v8.13.0
* NPM Version: 6.4.1
* postcss Version: 7.0.6
* postcss-less Version: 3.1.0

### LESS

```less
// web/test.less
.test {
	.foo( {
		width: calc(~"100% + 1px");
	} );
}

```

### Errors
When running `stylelint "web/test.less"`
```
web/test.less
 4:4  ✖  Unknown word   CssSyntaxError

error Command failed with exit code 2)
```

### Expected Behavior
No error.

### Actual Behavior
Error.

### How can we reproduce the behavior?
See above.
