### ISSUE TITLE
CssSyntaxError for single quotes in comment and value

### ISSUE THREAD

**Issue by dmowski** [shellscape/postcss-less#134]
* Node Version: 10.15.1
* NPM Version: 6.7.0
* postcss Version: 7.0.14
* postcss-less Version: 3.1.2
* stylelint Version: 9.10.1

Repository with example
https://github.com/dmowski/stylelint-bug-3943

### LESS
```less
// Dobule"quote
a:before {
  content: ""; //required str with Dobule quote for reproduce bug
}

// single'quote
a:before {
  content: ''; //required str with single quote for reproduce bug
}
```

### Errors

```
4:13
error
Unclosed string (CssSyntaxError)
```

### Expected Behavior
No warnings

### Actual Behavior
Warning by stylelint

### How can we reproduce the behavior?
https://github.com/dmowski/stylelint-bug-3943
npm i && npm run lint
