### ISSUE TITLE
'TypeError: this.getPosition is not a function' on parsing inline comments

### ISSUE THREAD

**Issue by FreekVR** [shellscape/postcss-less#165]
* Node Version: 14.8.1
* NPM Version: 6.14.14
* postcss Version: 8.3.11
* postcss-less Version: 5.0.0

### LESS

```less
.layout.layout--auth {
    display: flex;
    justify-content: center;
    min-height: 100vh;
    background: #000285 url('~assets/img/backgrounds/auth-bg.jpg'); // @TODO: Make responsive & smaller where possible
    background-size: cover;
    background-repeat: no-repeat;
    background-position: center center;

    @media @q-sm-min {
        align-items: center;
    }
}
```

### Errors 

```
TypeError: this.getPosition is not a function
    at LessParser.inlineComment (/home/freek/projects/asc-app/node_modules/postcss-less/lib/LessParser.js:72:28)
    at LessParser.isInlineComment (/home/freek/projects/asc-app/node_modules/postcss-less/lib/nodes/inline-comment.js:37:12)
    at LessParser.other (/home/freek/projects/asc-app/node_modules/postcss-less/lib/LessParser.js:157:36)
    at LessParser.parse (/home/freek/projects/asc-app/node_modules/postcss/lib/parser.js:75:16)
    at Object.parse (/home/freek/projects/asc-app/node_modules/postcss-less/lib/index.js:11:12)
    at LocalFixer.parse (/home/freek/projects/asc-app/node_modules/postcss-html/lib/html/parse-styles.js:96:18)
    at parseStyle (/home/freek/projects/asc-app/node_modules/postcss-html/lib/html/parse-styles.js:125:43)
    at /home/freek/projects/asc-app/node_modules/postcss-html/lib/html/parse-styles.js:138:18
    at Array.forEach (<anonymous>)
    at parseStyles (/home/freek/projects/asc-app/node_modules/postcss-html/lib/html/parse-styles.js:137:5)
```

### Expected Behavior
No error, parser succeeds

### Actual Behavior
Getting an error, could not even find a function with that name in any of the postcss-less files :(
